spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/easyui?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 200
mybatis:
  #使用通配符配置Mapper.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  #别名扫描包
  type-aliases-package: com.carapp.carscrapordermanager.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers: com.carapp.carscrapordermanager.config.MyMapper
  not-empty: true
  identity: mysql



pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
